language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go vet ./...
  - go test ./...
